services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false
      bind:
          $calendarExport: '@Cgoit\ContaoCalendarIcalBundle\Classes\CalendarExport'
          $calendarImport: '@Cgoit\ContaoCalendarIcalBundle\Classes\CalendarImport'
          $timezoneUtil: '@Cgoit\ContaoCalendarIcalBundle\Util\TimezoneUtil'
          $projectDir: '%kernel.project_dir%'
          $db: '@database_connection'
          $slug: '@contao.slug'
          $insertTagParser: '@contao.insert_tag.parser'

   Cgoit\ContaoCalendarIcalBundle\:
      resource: ../src/*
